---
title: "Coursera"
format: html
editor: visual
---

#swirl 
```{r}
# Set your working directory - CHANGE THIS TO YOUR ACTUAL PATH
setwd("C:/Users/saniy/Downloads/ExData_Plotting1-master/ExData_Plotting1-master")  

# Read the data
data <- read.csv("C:/Users/saniy/Downloads/exdata_data_household_power_consumption/household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE)

# Convert Date column to Date type
data$Date <- as.Date(data$Date, format="%d/%m/%Y")

# Subset for 2007-02-01 and 2007-02-02
subset_data <- data[data$Date >= "2007-02-01" & data$Date <= "2007-02-02", ]

# Convert numeric columns
cols <- c("Global_active_power","Global_reactive_power","Voltage",
          "Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
subset_data[cols] <- lapply(subset_data[cols], as.numeric)

# Create a datetime column
subset_data$datetime <- as.POSIXct(paste(subset_data$Date, subset_data$Time),
                                   format="%Y-%m-%d %H:%M:%S")
```
#Plot 1
```{r}
# =================== Plot 1 ===================
png("plot1.png", width=480, height=480)
hist(subset_data$Global_active_power,
     col="red",
     main="Global Active Power",
     xlab="Global Active Power (kilowatts)")
dev.off()
```
# ======== PLOT 2 ========
```{r}

# Plot 2: Line plot
png("plot2.png", width=480, height=480)
plot(subset_data$datetime, subset_data$Global_active_power,
     type="l",
     xlab="",
     ylab="Global Active Power (kilowatts)")
dev.off()
```
# Plot 3: Sub-metering
```{r}
png("plot3.png", width=480, height=480)
plot(subset_data$datetime, subset_data$Sub_metering_1,
     type="l",
     xlab="",
     ylab="Energy sub metering")
lines(subset_data$datetime, subset_data$Sub_metering_2, col="red")
lines(subset_data$datetime, subset_data$Sub_metering_3, col="blue")
legend("topright",
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),
       col=c("black","red","blue"),
       lty=1)
dev.off()
```
# ======== PLOT 4 ========
```{r}
# Plot 4: 2x2 panel
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))

# Top-left
plot(subset_data$datetime, subset_data$Global_active_power,
     type="l",
     xlab="",
     ylab="Global Active Power")

# Top-right
plot(subset_data$datetime, subset_data$Voltage,
     type="l",
     xlab="datetime",
     ylab="Voltage")

# Bottom-left
plot(subset_data$datetime, subset_data$Sub_metering_1,
     type="l",
     xlab="",
     ylab="Energy sub metering")
lines(subset_data$datetime, subset_data$Sub_metering_2, col="red")
lines(subset_data$datetime, subset_data$Sub_metering_3, col="blue")
legend("topright",
       legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),
       col=c("black","red","blue"),
       lty=1, bty="n")

# Bottom-right
plot(subset_data$datetime, subset_data$Global_reactive_power,
     type="l",
     xlab="datetime",
     ylab="Global_reactive_power")
```